<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Prism.Core" Version="9.0.537" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Northwind.DataAccess.Interfaces\Northwind.DataAccess.Interfaces.csproj" />
		<ProjectReference Include="..\Northwind.Data\Northwind.Data.csproj" />
		<ProjectReference Include="..\Northwind.Mvvm\Northwind.Mvvm.csproj" />
		<ProjectReference Include="..\Services\Northwind.Services.Interfaces\Northwind.Services.Interfaces.csproj" />
	</ItemGroup>

</Project>
