<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Northwind.Mvvm\Northwind.Mvvm.csproj" />
    <ProjectReference Include="..\Northwind.Services.Interfaces\Northwind.Services.Interfaces.csproj" />
  </ItemGroup>

</Project>
